language: erlang
sudo: false

env:
  global:
    - BASELINE=Nemo
    - PACKAGES="/repository" # Directory where filetree looks for packages
  matrix:
    - SMALLTALK="SqueakTrunk"
    - SMALLTALK="Squeak4.6"

addons:
  apt:
    packages:
    # 32-bit VM
    - libc6:i386
    # UUIDPlugin
    - libuuid1:i386

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O filetreeCI.zip https://github.com/fniephaus/filetreeCI/archive/master.zip
   - unzip -q filetreeCI.zip
   - cd filetreeCI-*
   - export FILETREE_CI_HOME="$(pwd)"

script: $FILETREE_CI_HOME/run.sh

after_success:
  - chmod +x $PROJECT_HOME/scripts/prepare_image.sh
  - $PROJECT_HOME/scripts/prepare_image.sh


#    Zzzzz  |\      _,,,--,,_        +-----------------------------+
#           /,`.-'`'   ._  \-;;,_    | Why is there always a cat   |
#          |,4-  ) )_   .;.(  `'-'   | on whatever you're editing? |
#         '---''(_/._)-'(_\_)        +-----------------------------+
